project:
  type: website
  output-dir: /docs

website:
  title: "Jarred Ezra Randall"
  favicon: "assets/profile.png"
  navbar:
    left:
      - text: Home
        href: index.qmd
      - text: Projects
        href: Projects.qmd
      - text: Resume
        href: Resume.qmd
      - text: Music
        href: Music.qmd
    right:
      - icon: linkedin
        href: "https://www.linkedin.com/in/jarredrandall/"
      - icon: github
        href: "https://github.com/JarredERandall/"
  search: 
    location: navbar
    type: overlay
  page-navigation: true
  page-footer:
    center: |
      [Contact Me](mailto:JarredERandall@gmail.com)
    left: |
      Powered by [Quarto](https://quarto.org)
    right: |
      &#169; 2024 Jarred Ezra Randall
    background: "#f8f9fa"

format:
  html:
    theme: 
      light: cosmo
    css: styles.css
    toc: true
    pagetitle: "{{< meta title >}} | Jarred Randall"
    smooth-scroll: true

editor: source
