project:
  type: website
  output-dir: docs

website:
  title: "Jarred Ezra Randall"
  favicon: "profile.jpeg"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - projects.qmd 
      - resume.qmd
    right:
      - icon: linkedin
        href: "www.linkedin.com/in/jarred-randall-8275171a3"
      - icon: github
        href: "https://github.com/JarredERandall"
  search: 
    location: navbar
    type: overlay
  page-navigation: true
      
  page-footer:
    center: |
      [Contact Me](mailto:jarrederandall@gmail.com)
    left: |
      Powered by [Quarto](https://quarto.org)
    right: |
      &#169; 2024 Jarred Ezra Randall
    background: "#f8f9fa"

format:
  html:
    theme: 
      light: cosmo
    css: styles.css
    toc: true
    pagetitle: "{{< meta title >}} | Jarred Randall"
    smooth-scroll: true

editor: source