project:
  type: website
  output-dir: docs

format:
  html:
    toc: true
    theme: cosmo
    css: styles.css
    title-prefix: "Jarred Ezra Randall"
    pagetitle: '{{< meta title >}} | Jarred Ezra Randall'
    smooth-scroll: true
    metadata:
      document-css: false
      link-citations: true
      date-format: long
      lang: en
      editor: source
    about:
      template: jolla
      image-width: 20em
      image-shape: round
      links:
        - icon: linkedin
          text: LinkedIn
          href: 'https://www.linkedin.com/in/jarredrandall/'
        - icon: github
          text: Github
          href: 'https://github.com/JarredERandall/'
        - icon: envelope
          text: Contact me
          href: 'mailto:jarrederandall@gmail.com'
