project:
  type: website
  output-dir: docs

website:
  title: "Jarred Ezra Randall"
  favicon: "assets/profile.png"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - Projects.qmd 
      - Resume.qmd
      - Music.qmd
    right:
      - icon: linkedin
        href: "https://www.linkedin.com/in/jarredrandall/"
      - icon: github
        href: "https://github.com/JarredERandall/"
  search: 
    location: navbar
    type: overlay
  page-navigation: true
      
  page-footer:
    center: |
      [Contact Me](mailto:JarredERandall@gmail.com)
    left: |
      Powered by [Quarto](https://quarto.org)
    right: |
      &#169; 2024 Jarred Ezra Randall

format:
  html:
    theme: 
      light: cosmo
    css: styles.css
    toc: true
    pagetitle: "{{< meta title >}} | Jarred Ezra Randall"
    smooth-scroll: true

editor: source
